import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Site branding
    siteName: 'kiani.exchange',
    siteTitle: 'Kiani Exchange - Premium AI Services',
    
    // Login page
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to your account to access premium AI services',
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    signInButton: 'Sign In',
    forgotPassword: 'Forgot your password?',
    noAccount: "Don't have an account?",
    signUpLink: 'Sign up here',
    demoCredentials: 'Demo Credentials:',
    demoUser: 'User',
    demoAdmin: 'Admin',
    demoSuperAdmin: 'Super Admin',
    
    // Register page
    createAccount: 'Create Account',
    joinPlatform: 'Join our platform to access premium AI services',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    agreeToTerms: 'I agree to the Terms of Service and Privacy Policy',
    createAccountButton: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in here',
    
    // Validation messages
    emailRequired: 'Email is required',
    emailInvalid: 'Email is invalid',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 6 characters',
    nameRequired: 'Full name is required',
    passwordsNotMatch: 'Passwords do not match',
    termsRequired: 'You must agree to the terms',
    loginFailed: 'Login failed. Please check your credentials.',
    invalidCredentials: 'Invalid email or password',
    
    home: 'Home',
    services: 'Services',
    dashboard: 'Dashboard',
    login: 'Login',
    signup: 'Sign Up',
    payments: 'Online Service Payments',
    toggle: 'FA',
    logout: 'Logout',
    welcomeBackDashboard: 'Welcome back, {email}! ',
    dashboardIntro: "Here's an overview of your account and recent activity.",
    accountBalance: 'Account Balance',
    totalOrders: 'Total Orders',
    pendingOrders: 'Pending Orders',
    completedOrders: 'Completed Orders',
    quickActions: 'Quick Actions',
    newOrder: 'New Order',
    placeNewOrder: 'Place a new service order',
    viewOrders: 'View Orders',
    checkOrderHistory: 'Check your order history',
    support: 'Support',
    getHelpSupport: 'Get help and support',
    profile: 'Profile',
    manageProfile: 'Manage your profile',
    addToBasket: 'Add to Basket',
    basket: 'Basket',
    emptyBasket: 'Your basket is empty',
    subtotal: 'Subtotal',
    tax: 'Tax',
    vat: 'VAT',
    total: 'Total',
    pay: 'Pay',
    availableServices: 'Available Services',
    paymentsIntro: 'Services available to purchase',
    loadingDashboard: 'Loading Dashboard...',
    llmServices: 'LLM Services',
    heroBadge: '⚡ Trusted by 10,000+ users worldwide',
    heroTitle: 'Access Premium AI Services with Confidence',
    heroDescription: 'Your gateway to cutting-edge AI tools and services. Secure payments, verified providers, and dedicated support for all your AI needs.',
    goToDashboard: 'Go to Dashboard →',
    getStarted: 'Get Started Free →',
    browseServices: 'Browse Services',
    statsActiveUsers: 'Active Users',
    statsAIServices: 'AI Services',
    statsCountries: 'Countries',
    statsUptime: 'Uptime',
    whyChooseTitle: 'Why Choose Our Platform?',
    whyChooseDescription: 'We provide a secure, reliable, and user-friendly platform for accessing premium AI services from around the world.',
    featureSecureTitle: 'Secure & Verified',
    featureSecureDesc: 'KYC verification and secure payment processing ensure your safety and compliance.',
    featurePricingTitle: 'Real-time Pricing',
    featurePricingDesc: 'Live USD to Toman conversion with transparent pricing and no hidden fees.',
    featureSupportTitle: '24/7 Support',
    featureSupportDesc: 'Dedicated customer support team ready to help you with any questions.',
    featurePremiumTitle: 'Premium Services',
    featurePremiumDesc: 'Access to cutting-edge AI services from leading providers worldwide.',
    ctaTitle: 'Ready to Get Started?',
    ctaDescription: 'Join thousands of users who trust our platform for their AI service needs. Start your journey today with our secure and reliable platform.',
    ctaGoDashboard: 'Go to Dashboard →',
    ctaCreateAccount: 'Create Free Account →',
    ctaSignIn: 'Sign In',
    ctaNoSetup: '✓ No setup fees',
    ctaSecurePayments: '✓ Secure payments',
    ctaSupport: '✓ 24/7 support',
    serviceNotFound: 'Service not found',
    // Services page translations
    llmModelsTitle: 'LLM Language Models',
    llmModelsDescription: 'Access premium Large Language Models from leading AI providers. All prices shown in Iranian Toman with real-time conversion.',
    exchangeRate: '1 USD = {rate} ﷼',
    searchPlaceholder: 'Search services...',
    sortByName: 'Name (A-Z)',
    sortByPrice: 'Price (Low to High)',
    sortByRating: 'Rating (High to Low)',
    sortByPopularity: 'Most Popular',
    showingResults: 'Showing {count} of {total} LLM models',
    languageModel: 'Language Model',
    keyFeatures: 'Key Features',
    moreFeatures: '+{count} more',
    rating: 'Rating',
    response: 'Response',
    popular: 'Popular',
    orderNow: 'Order Now',
    noModelsFound: 'No LLM models found',
    noModelsDescription: 'Try adjusting your search criteria.',
    clearSearch: 'Clear Search',
    secureReliableTitle: 'Secure & Reliable',
    secureReliableDesc: 'All LLM models are hosted on secure infrastructure with 99.9% uptime guarantee.',
    transparentPricingTitle: 'Transparent Pricing',
    transparentPricingDesc: 'No hidden fees. Pay only for what you use with real-time currency conversion.',
    fastPerformanceTitle: 'Fast Performance',
    fastPerformanceDesc: 'Optimized APIs with low latency and high throughput for the best user experience.',
    qualityAssuredTitle: 'Quality Assured',
    qualityAssuredDesc: 'All models are tested and verified to meet the highest quality standards.',
    loadingServices: 'Loading services...',
    loginToOrder: 'Please log in to order services',
    orderingService: 'Ordering {service}. This feature will be implemented with payment integration.',
    pros: 'Pros',
    bestFor: 'Best For',
    morePros: '+{count} more pros',
    perMonth: 'per month',
  },
  fa: {
    // Site branding
    siteName: 'kiani.exchange',
    siteTitle: 'کیانی اکسچنج - خدمات هوش مصنوعی پریمیوم',
    
    // Login page
    welcomeBack: 'خوش آمدید',
    signInSubtitle: 'برای دسترسی به خدمات هوش مصنوعی پریمیوم وارد حساب کاربری خود شوید',
    emailAddress: 'آدرس ایمیل',
    password: 'رمز عبور',
    enterEmail: 'ایمیل خود را وارد کنید',
    enterPassword: 'رمز عبور خود را وارد کنید',
    signInButton: 'ورود',
    forgotPassword: 'رمز عبور خود را فراموش کرده‌اید؟',
    noAccount: 'حساب کاربری ندارید؟',
    signUpLink: 'اینجا ثبت نام کنید',
    demoCredentials: 'اطلاعات نمونه:',
    demoUser: 'کاربر',
    demoAdmin: 'مدیر',
    demoSuperAdmin: 'مدیر کل',
    
    // Register page
    createAccount: 'ایجاد حساب کاربری',
    joinPlatform: 'به پلتفرم ما بپیوندید تا به خدمات هوش مصنوعی پریمیوم دسترسی پیدا کنید',
    fullName: 'نام کامل',
    enterFullName: 'نام کامل خود را وارد کنید',
    confirmPassword: 'تأیید رمز عبور',
    confirmPasswordPlaceholder: 'رمز عبور خود را تأیید کنید',
    agreeToTerms: 'من با شرایط خدمات و سیاست حفظ حریم خصوصی موافقم',
    createAccountButton: 'ایجاد حساب کاربری',
    alreadyHaveAccount: 'قبلاً حساب کاربری دارید؟',
    signInLink: 'اینجا وارد شوید',
    
    // Validation messages
    emailRequired: 'ایمیل الزامی است',
    emailInvalid: 'ایمیل نامعتبر است',
    passwordRequired: 'رمز عبور الزامی است',
    passwordMinLength: 'رمز عبور باید حداقل ۶ کاراکتر باشد',
    nameRequired: 'نام کامل الزامی است',
    passwordsNotMatch: 'رمزهای عبور مطابقت ندارند',
    termsRequired: 'باید با شرایط موافقت کنید',
    loginFailed: 'ورود ناموفق. لطفاً اطلاعات خود را بررسی کنید.',
    invalidCredentials: 'ایمیل یا رمز عبور نامعتبر',
    
    home: 'خانه',
    services: 'خدمات',
    dashboard: 'داشبورد',
    login: 'ورود',
    signup: 'ثبت‌نام',
    payments: 'پرداخت های ارزی',
    toggle: 'EN',
    logout: 'خروج',
    welcomeBackDashboard: 'خوش آمدید، {email}!',
    dashboardIntro: 'در اینجا نمایی کلی از حساب و فعالیت اخیر شما است.',
    accountBalance: 'موجودی حساب',
    totalOrders: 'کل سفارشات',
    pendingOrders: 'سفارشات در انتظار',
    completedOrders: 'سفارشات تکمیل شده',
    quickActions: 'اقدامات سریع',
    newOrder: 'سفارش جدید',
    placeNewOrder: 'ثبت سفارش جدید',
    viewOrders: 'مشاهده سفارشات',
    checkOrderHistory: 'بررسی تاریخچه سفارشات',
    support: 'پشتیبانی',
    getHelpSupport: 'دریافت کمک و پشتیبانی',
    profile: 'پروفایل',
    manageProfile: 'مدیریت پروفایل',
    addToBasket: 'افزودن به سبد خرید',
    basket: 'سبد خرید',
    emptyBasket: 'سبد خرید شما خالی است',
    subtotal: 'جمع جزء',
    tax: 'مالیات',
    vat: 'مالیات بر ارزش افزوده',
    total: 'مجموع',
    pay: 'پرداخت',
    availableServices: 'خدمات موجود',
    paymentsIntro: 'خدمات قابل خرید',
    loadingDashboard: 'در حال بارگذاری داشبورد...',
    llmServices: 'سرویس های LLM',
    heroBadge: '⚡ مورد اعتماد بیش از ۱۰٬۰۰۰ کاربر در سراسر جهان',
    heroTitle: 'با اطمینان به خدمات پریمیوم هوش مصنوعی دسترسی پیدا کنید',
    heroDescription: 'دروازه شما به ابزارها و خدمات پیشرفته هوش مصنوعی. پرداخت امن، ارائه‌دهندگان تایید شده و پشتیبانی اختصاصی برای تمام نیازهای شما.',
    goToDashboard: 'رفتن به داشبورد →',
    getStarted: 'شروع رایگان →',
    browseServices: 'مشاهده خدمات',
    statsActiveUsers: 'کاربران فعال',
    statsAIServices: 'خدمات هوش مصنوعی',
    statsCountries: 'کشورها',
    statsUptime: 'پایداری',
    whyChooseTitle: 'چرا پلتفرم ما؟',
    whyChooseDescription: 'ما پلتفرمی امن، قابل اعتماد و کاربرپسند برای دسترسی به خدمات پریمیوم هوش مصنوعی از سراسر جهان فراهم می‌کنیم.',
    featureSecureTitle: 'امن و تایید شده',
    featureSecureDesc: 'تایید هویت KYC و پردازش پرداخت امن، امنیت و انطباق شما را تضمین می‌کند.',
    featurePricingTitle: 'قیمت‌گذاری لحظه‌ای',
    featurePricingDesc: 'تبدیل زنده دلار به تومان با قیمت شفاف و بدون هزینه پنهان.',
    featureSupportTitle: 'پشتیبانی ۲۴/۷',
    featureSupportDesc: 'تیم پشتیبانی اختصاصی آماده پاسخگویی به هرگونه سوال شماست.',
    featurePremiumTitle: 'خدمات پریمیوم',
    featurePremiumDesc: 'دسترسی به جدیدترین خدمات هوش مصنوعی از ارائه‌دهندگان برتر جهان.',
    ctaTitle: 'آماده شروع هستید؟',
    ctaDescription: 'به هزاران کاربری بپیوندید که برای نیازهای خدمات هوش مصنوعی خود به پلتفرم ما اعتماد دارند. همین امروز با پلتفرم امن و قابل اعتماد ما شروع کنید.',
    ctaGoDashboard: 'رفتن به داشبورد →',
    ctaCreateAccount: 'ایجاد حساب رایگان →',
    ctaSignIn: 'ورود',
    ctaNoSetup: '✓ بدون هزینه راه‌اندازی',
    ctaSecurePayments: '✓ پرداخت امن',
    ctaSupport: '✓ پشتیبانی ۲۴/۷',
    serviceNotFound: 'سرویس یافت نشد',
    // Services page translations
    llmModelsTitle: 'مدل‌های زبانی LLM',
    llmModelsDescription: 'دسترسی به مدل‌های زبانی پریمیوم از ارائه‌دهندگان پیشرو هوش مصنوعی. تمام قیمت‌ها به تومان ایران با تبدیل لحظه‌ای نمایش داده می‌شود.',
    exchangeRate: '۱ دلار = {rate} ﷼',
    searchPlaceholder: 'جستجوی خدمات...',
    sortByName: 'نام (الف-ی)',
    sortByPrice: 'قیمت (کم به زیاد)',
    sortByRating: 'امتیاز (زیاد به کم)',
    sortByPopularity: 'محبوب‌ترین',
    showingResults: 'نمایش {count} از {total} مدل LLM',
    languageModel: 'مدل زبانی',
    keyFeatures: 'ویژگی‌های کلیدی',
    moreFeatures: '+{count} بیشتر',
    rating: 'امتیاز',
    response: 'پاسخ',
    popular: 'محبوبیت',
    orderNow: 'سفارش دهید',
    noModelsFound: 'هیچ مدل LLM یافت نشد',
    noModelsDescription: 'معیارهای جستجوی خود را تنظیم کنید.',
    clearSearch: 'پاک کردن جستجو',
    secureReliableTitle: 'امن و قابل اعتماد',
    secureReliableDesc: 'تمام مدل‌های LLM روی زیرساخت امن با ضمانت ۹۹.۹٪ آپتایم میزبانی می‌شوند.',
    transparentPricingTitle: 'قیمت‌گذاری شفاف',
    transparentPricingDesc: 'بدون هزینه پنهان. فقط برای آنچه استفاده می‌کنید با تبدیل ارز لحظه‌ای پرداخت کنید.',
    fastPerformanceTitle: 'عملکرد سریع',
    fastPerformanceDesc: 'API های بهینه شده با تأخیر کم و توان عملیاتی بالا برای بهترین تجربه کاربری.',
    qualityAssuredTitle: 'کیفیت تضمین شده',
    qualityAssuredDesc: 'تمام مدل‌ها آزمایش و تایید شده‌اند تا بالاترین استانداردهای کیفی را داشته باشند.',
    loadingServices: 'بارگذاری خدمات...',
    loginToOrder: 'لطفاً برای سفارش خدمات وارد شوید',
    orderingService: 'سفارش {service}. این ویژگی با یکپارچگی پرداخت پیاده‌سازی خواهد شد.',
    pros: 'مزایا',
    bestFor: 'بهترین برای',
    morePros: '+{count} مزیت بیشتر',
    perMonth: 'در ماه',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;
  const toggleLanguage = () => setLang(prev => prev === 'en' ? 'fa' : 'en');

  useEffect(() => {
    document.documentElement.dir = lang === 'fa' ? 'rtl' : 'ltr';
    document.body.classList.toggle('rtl', lang === 'fa');
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
